# Generated by Django 4.2.1 on 2023-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksSymbolModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stock_pkey', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('stock_price', models.TextField()),
            ],
            options={
                'verbose_name': 'Stock Price Ticker',
                'verbose_name_plural': 'Stock Price Tickers',
                'db_table': 'Stock_Price_Ticker',
                'abstract': False,
            },
        ),
    ]
