# Generated by Django 4.2.1 on 2023-06-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock_indices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockssymbolmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockssymbolmodel',
            name='modified_at',
        ),
    ]
