# Generated by Django 4.2.1 on 2023-06-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_customusermodel_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
